package ui;

import java.awt.Color;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

public class FormSeleccionNodosDistancias extends javax.swing.JPanel {

    public FormSeleccionNodosDistancias() {
        initComponents();
        pathDistance.setText(main.distancesPath);
        pathNodes.setText(main.nodesPath);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ButtonSelectNodes = new javax.swing.JLabel();
        pathNodes = new javax.swing.JLabel();
        ButtonSelectDistance = new javax.swing.JLabel();
        pathDistance = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ButtonConfirm = new javax.swing.JLabel();

        setBackground(new java.awt.Color(253, 253, 253));

        ButtonSelectNodes.setBackground(new java.awt.Color(201, 214, 223));
        ButtonSelectNodes.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        ButtonSelectNodes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ButtonSelectNodes.setText("...");
        ButtonSelectNodes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonSelectNodes.setOpaque(true);
        ButtonSelectNodes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonSelectNodesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ButtonSelectNodesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ButtonSelectNodesMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ButtonSelectNodesMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ButtonSelectNodesMouseReleased(evt);
            }
        });

        pathNodes.setBackground(new java.awt.Color(255, 255, 255));
        pathNodes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pathNodes.setOpaque(true);

        ButtonSelectDistance.setBackground(new java.awt.Color(201, 214, 223));
        ButtonSelectDistance.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        ButtonSelectDistance.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ButtonSelectDistance.setText("...");
        ButtonSelectDistance.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonSelectDistance.setOpaque(true);
        ButtonSelectDistance.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonSelectDistanceMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ButtonSelectDistanceMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ButtonSelectDistanceMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ButtonSelectDistanceMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ButtonSelectDistanceMouseReleased(evt);
            }
        });

        pathDistance.setBackground(new java.awt.Color(255, 255, 255));
        pathDistance.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pathDistance.setOpaque(true);

        jLabel1.setText("Selecciona Archivo con la informacion de los Nodos (.csv)");

        jLabel2.setText("Selecciona Archivo con la informacion de las Distancias(.csv)");

        ButtonConfirm.setBackground(new java.awt.Color(201, 214, 223));
        ButtonConfirm.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        ButtonConfirm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ButtonConfirm.setText("Confirmar");
        ButtonConfirm.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonConfirm.setOpaque(true);
        ButtonConfirm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonConfirmMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ButtonConfirmMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ButtonConfirmMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ButtonConfirmMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ButtonConfirmMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ButtonSelectDistance, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pathDistance, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ButtonSelectNodes, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pathNodes, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ButtonConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ButtonSelectNodes, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(pathNodes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(17, 17, 17)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ButtonSelectDistance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pathDistance, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                .addComponent(ButtonConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonSelectNodesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonSelectNodesMouseClicked
        // creamos el objeto JFileChooser Para seleccionar los archivos
        JFileChooser fc = new JFileChooser();
        // Abrimos la ventana, guardamos la opcion seleccionada por el usuario
        int seleccion = fc.showOpenDialog(this);

        // si el usuario pincha en aceptar
        if (seleccion == JFileChooser.APPROVE_OPTION) {
            // seleccionamos el fichero
            File fichero = fc.getSelectedFile();
            //Escribe la ruta del fichero seleccionado en el campo de texto
            pathNodes.setText(fichero.getAbsolutePath());
        }
    }//GEN-LAST:event_ButtonSelectNodesMouseClicked

    private void ButtonSelectDistanceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonSelectDistanceMouseClicked
        // creamos el objeto JFileChooser Para seleccionar los archivos
        JFileChooser fc = new JFileChooser();
        // Abrimos la ventana, guardamos la opcion seleccionada por el usuario
        int seleccion = fc.showOpenDialog(this);

        // si el usuario pincha en aceptar
        if (seleccion == JFileChooser.APPROVE_OPTION) {
            // seleccionamos el fichero
            File fichero = fc.getSelectedFile();
            //Escribe la ruta del fichero seleccionado en el campo de texto
            pathDistance.setText(fichero.getAbsolutePath());
        }
    }//GEN-LAST:event_ButtonSelectDistanceMouseClicked

    private void ButtonConfirmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonConfirmMouseClicked

        /*
        este boton nos sirve para guardar las rutas de los archivos que tienen la informacion de los nodos y de las distancias
        Este metodo tiene la funcionalidad de comprobar si se seleccionaron archivos para guardar las rutas de los archivos.
        
        tambine maneja los mensajes de error o de confirmacion para el usuario
         */
        if (pathDistance.getText() == "" && pathNodes.getText() == "") {
            JOptionPane.showMessageDialog(null, "Tienes que seleccionar por lo menor un arhcivo con la informacion de los nodos.", "Error Al Seleccionar el Archivo", JOptionPane.ERROR_MESSAGE);
        }
        if (pathNodes.getText() != "") {
            main.nodesPath = pathNodes.getText();
        }
        if (pathDistance.getText() != "") {
            main.distancesPath = pathDistance.getText();
        }

        if (pathNodes.getText() != "" && pathDistance.getText() != "") {
            JOptionPane.showMessageDialog(null, "Ruta de los archivos con la informacion de los Nodos y de las Distancias Guardadas.", "Informacion Guardada", JOptionPane.INFORMATION_MESSAGE);
        } else if (pathNodes.getText() != "") {
            JOptionPane.showMessageDialog(null, "Ruta del archivo con la informacion de los Nodos Guardada.", "Informacion de Nodos Guardada", JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_ButtonConfirmMouseClicked
    
    // metodos de UI sin importancia realmente 
    private void ButtonSelectNodesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonSelectNodesMouseEntered
        ButtonSelectNodes.setBackground(new Color(82,97,107));
        ButtonSelectNodes.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_ButtonSelectNodesMouseEntered

    private void ButtonSelectNodesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonSelectNodesMouseExited
        ButtonSelectNodes.setBackground(new Color(201,214,223));
        ButtonSelectNodes.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_ButtonSelectNodesMouseExited

    private void ButtonSelectNodesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonSelectNodesMousePressed
        ButtonSelectNodes.setBackground(new Color(30,32,34));
    }//GEN-LAST:event_ButtonSelectNodesMousePressed

    private void ButtonSelectNodesMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonSelectNodesMouseReleased
        ButtonSelectNodes.setBackground(new Color(82,97,107));
    }//GEN-LAST:event_ButtonSelectNodesMouseReleased

    private void ButtonSelectDistanceMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonSelectDistanceMouseEntered
        ButtonSelectDistance.setBackground(new Color(82,97,107));
        ButtonSelectDistance.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_ButtonSelectDistanceMouseEntered

    private void ButtonSelectDistanceMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonSelectDistanceMouseExited
        ButtonSelectDistance.setBackground(new Color(201,214,223));
        ButtonSelectDistance.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_ButtonSelectDistanceMouseExited

    private void ButtonSelectDistanceMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonSelectDistanceMousePressed
        ButtonSelectDistance.setBackground(new Color(30,32,34));
    }//GEN-LAST:event_ButtonSelectDistanceMousePressed

    private void ButtonSelectDistanceMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonSelectDistanceMouseReleased
        ButtonSelectDistance.setBackground(new Color(82,97,107));
    }//GEN-LAST:event_ButtonSelectDistanceMouseReleased

    private void ButtonConfirmMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonConfirmMouseEntered
        ButtonConfirm.setBackground(new Color(82,97,107));
        ButtonConfirm.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_ButtonConfirmMouseEntered

    private void ButtonConfirmMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonConfirmMouseExited
        ButtonConfirm.setBackground(new Color(201,214,223));
        ButtonConfirm.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_ButtonConfirmMouseExited

    private void ButtonConfirmMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonConfirmMousePressed
        ButtonConfirm.setBackground(new Color(30,32,34));
    }//GEN-LAST:event_ButtonConfirmMousePressed

    private void ButtonConfirmMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonConfirmMouseReleased
        ButtonConfirm.setBackground(new Color(82,97,107));
    }//GEN-LAST:event_ButtonConfirmMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ButtonConfirm;
    private javax.swing.JLabel ButtonSelectDistance;
    private javax.swing.JLabel ButtonSelectNodes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel pathDistance;
    private javax.swing.JLabel pathNodes;
    // End of variables declaration//GEN-END:variables
}
